// Regenerate the bundled fallback datasets from the live mod source via the same pipeline the browser uses.
// Run: node scratch/export_snapshots.js
// Writes docs/data/weapons_data.js, weapons_db.json, ammos_data.js, ammos_db.json, magazines_blueprints_data.js.
const fs = require('fs');
const path = require('path');
const SP = require('../docs/source_pipeline.js');

const HEADER = '// GENERATED by scratch/export_snapshots.js — live source parsed via source_pipeline.js.\n'
  + '// This is a fallback snapshot only; the Studio parses CoreParts/*.cs + Content/Data/*.sbc live.\n'
  + '// Do not hand-edit; regenerate via: node scratch/export_snapshots.js\n\n';

const cs = {};
for (const f of fs.readdirSync('CoreParts')) {
  if (f.endsWith('.cs') && !/Animations/.test(f) && !f.includes('Animation')) {
    cs[f] = fs.readFileSync(path.join('CoreParts', f), 'utf8');
  }
}

const sbc = {
  magazines: ['AmmoMagazines_Ship.sbc', 'AmmoMagazines_Handheld.sbc']
    .map(f => fs.readFileSync(path.join('Content', 'Data', f), 'utf8')),
  blueprints: fs.readFileSync(path.join('Content', 'Data', 'Blueprints.sbc'), 'utf8'),
  cubeBlocks: {},
};
for (const f of fs.readdirSync(path.join('Content', 'Data', 'CubeBlocks'))) {
  if (f.endsWith('.sbc')) sbc.cubeBlocks[f] = fs.readFileSync(path.join('Content', 'Data', 'CubeBlocks', f), 'utf8');
}

const ovText = fs.readFileSync('docs/data/studio_overrides.js', 'utf8');
const ov = JSON.parse(ovText.slice(ovText.indexOf('=') + 1).trim().replace(/;\s*$/, ''));

const d = SP.buildStudioData(cs, sbc, ov);
if (d.errors.length) { console.error('BUILD ERRORS:', d.errors); process.exit(1); }

const outDir = 'docs/data';

const weaponsJs = HEADER + 'const BUNDLED_WEAPONS_DATA = ' + JSON.stringify(d.weapons, null, 2) + ';\n';
fs.writeFileSync(path.join(outDir, 'weapons_data.js'), weaponsJs);
fs.writeFileSync(path.join(outDir, 'weapons_db.json'), JSON.stringify(d.weapons, null, 2));

fs.writeFileSync(path.join(outDir, 'ammos_data.js'), ammosJs);
fs.writeFileSync(path.join(outDir, 'ammos_db.json'), JSON.stringify(d.ammos, null, 2));

const magsJs = HEADER + 'const MAGAZINES_BLUEPRINTS_DATA = ' + JSON.stringify(d.magazines, null, 2) + ';\n';
fs.writeFileSync(path.join(outDir, 'magazines_blueprints_data.js'), magsJs);

console.log('Wrote snapshots:');
console.log('  weapons     :', d.weapons.length, 'entries');
console.log('  ammos       :', Object.keys(d.ammos).length, 'entries');
console.log('  magazines   :', d.magazines.length, 'entries');
console.log('  warnings    :', d.warnings.length);
