// Regenerate the bundled fallback datasets from the live mod source via the same pipeline the browser uses.
// Run: node scratch/export_snapshots.js
// Writes studio/data/weapons_data.js, weapons_db.json, ammos_data.js, ammos_db.json, magazines_blueprints_data.js,
// wc_defs_data.js (lossless def trees), and wc_schema.js (Structure.cs signature + typed schema).
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const SP = require('../studio/source_pipeline.js');

// Working copy is CRLF (core.autocrlf=true); write generated files the same way.
function writeCrlf(file, text) {
  fs.writeFileSync(file, text.replace(/\r\n/g, '\n').replace(/\n/g, '\r\n'));
}

const HEADER = '// GENERATED by scratch/export_snapshots.js — live source parsed via source_pipeline.js.\n'
  + '// This is a fallback snapshot only; the Studio parses CoreParts/*.cs + Content/Data/*.sbc live.\n'
  + '// Do not hand-edit; regenerate via: node scratch/export_snapshots.js\n\n';

const cs = {};
for (const f of fs.readdirSync('CoreParts')) {
  if (f.endsWith('.cs') && !/Animations/.test(f) && !f.includes('Animation')) {
    cs[f] = fs.readFileSync(path.join('CoreParts', f), 'utf8');
  }
}

const sbc = {
  magazines: ['AmmoMagazines_Ship.sbc', 'AmmoMagazines_Handheld.sbc']
    .map(f => fs.readFileSync(path.join('Content', 'Data', f), 'utf8')),
  blueprints: fs.readFileSync(path.join('Content', 'Data', 'Blueprints.sbc'), 'utf8'),
  cubeBlocks: {},
};
for (const f of fs.readdirSync(path.join('Content', 'Data', 'CubeBlocks'))) {
  if (f.endsWith('.sbc')) sbc.cubeBlocks[f] = fs.readFileSync(path.join('Content', 'Data', 'CubeBlocks', f), 'utf8');
}

const curationText = fs.readFileSync('studio/data/curation.js', 'utf8');
const curation = JSON.parse(curationText.slice(curationText.indexOf('=') + 1).trim().replace(/;\s*$/, ''));

const d = SP.buildStudioData(cs, sbc, curation);
if (d.errors.length) { console.error('BUILD ERRORS:', d.errors); process.exit(1); }

const outDir = 'studio/data';

const weaponsJs = HEADER + 'const BUNDLED_WEAPONS_DATA = ' + JSON.stringify(d.weapons, null, 2) + ';\n';
writeCrlf(path.join(outDir, 'weapons_data.js'), weaponsJs);
writeCrlf(path.join(outDir, 'weapons_db.json'), JSON.stringify(d.weapons, null, 2));

const ammosJs = HEADER + 'const BUNDLED_AMMOS_DATA = ' + JSON.stringify(d.ammos, null, 2) + ';\n';
writeCrlf(path.join(outDir, 'ammos_data.js'), ammosJs);
writeCrlf(path.join(outDir, 'ammos_db.json'), JSON.stringify(d.ammos, null, 2));

const magsJs = HEADER + 'const MAGAZINES_BLUEPRINTS_DATA = ' + JSON.stringify(d.magazines, null, 2) + ';\n';
writeCrlf(path.join(outDir, 'magazines_blueprints_data.js'), magsJs);

// WeaponCore schema signature: the Studio diffs this against upstream CoreDefinitions.cs on page load
const structText = fs.readFileSync(path.join('CoreParts', 'script', 'Structure.cs'), 'utf8').replace(/^﻿/, '').replace(/\r/g, '');
const wcSig = SP.extractWcSchema(structText);
const prevSchemaText = fs.existsSync(path.join(outDir, 'wc_schema.js')) ? fs.readFileSync(path.join(outDir, 'wc_schema.js'), 'utf8') : '';
const prevVersion = (prevSchemaText.match(/"version":\s*"([^"]+)"/) || [])[1] || 'v0.75';
const wcSchema = {
  version: prevVersion,
  structureHash: crypto.createHash('sha1').update(structText).digest('hex').slice(0, 12),
  fileSize: structText.length,
  totalEnums: Object.keys(wcSig.enums).length,
  totalStructs: Object.keys(wcSig.structs).length,
  upstream: { repo: 'Ash-LikeSnow/WeaponCore', branch: 'master', path: 'Data/Scripts/CoreSystems/Definitions/CoreDefinitions.cs' },
  enums: wcSig.enums,
  structs: wcSig.structs,
  // Qualified type tree + CoreParts field comments drive the Studio's full-field editor and C# serializer
  types: SP.extractWcTypes(structText),
  help: SP.extractFieldHelp(cs),
};
writeCrlf(path.join(outDir, 'wc_schema.js'), HEADER + 'window.GVK_WC_SCHEMA = ' + JSON.stringify(wcSchema, null, 2) + ';\n');

// Lossless def trees (ammos, weapons, shared helpers) for full-field editing and export
writeCrlf(path.join(outDir, 'wc_defs_data.js'), HEADER + 'const BUNDLED_WC_DEFS = ' + JSON.stringify(d.wcDefs) + ';\n');

console.log('Wrote snapshots:');
console.log('  weapons     :', d.weapons.length, 'entries');
console.log('  ammos       :', Object.keys(d.ammos).length, 'entries');
console.log('  magazines   :', d.magazines.length, 'entries');
console.log('  warnings    :', d.warnings.length);
console.log('  wc schema   :', wcSchema.totalEnums, 'enums,', wcSchema.totalStructs, 'structs @', wcSchema.structureHash);
