// One-time migration: extract presentation-only fields from the bundled hand-typed datasets
// into docs/data/studio_overrides.js. Everything numeric stays source-derived (C#/SBC).
// Run: node scratch/migrate_overrides.js
const fs = require('fs'), path = require('path');
const dataDir = path.join(__dirname, '..', 'docs', 'data');
const iconsDir = path.join(__dirname, '..', 'docs', 'icons');
const diskIcons = new Set(fs.existsSync(iconsDir) ? fs.readdirSync(iconsDir) : []);

function loadBundled(file) {
  let s = fs.readFileSync(path.join(dataDir, file), 'utf8');
  s = s.replace(/^\/\/.*$/gm, '');
  const i = s.indexOf('=');
  return JSON.parse(s.slice(i + 1).trim().replace(/;\s*$/, ''));
}

const weapons = loadBundled('weapons_data.js');
const mags = loadBundled('magazines_blueprints_data.js');

function resolveIconFile(w) {
  const iconBase = path.basename(w.icon || '');
  if (diskIcons.has(iconBase)) return 'icons/' + iconBase;
  const stripped = iconBase.replace(/^[LS]__/, '');
  if (diskIcons.has(stripped)) return 'icons/' + stripped;
  if (diskIcons.has(w.subtypeId + '.png')) return 'icons/' + w.subtypeId + '.png';
  if (w.subtypeId === 'LargeGatlingTurret') return 'icons/L__Gatling_Turret.png';
  if (w.subtypeId === 'LargeMissileTurret') return 'icons/L__Missile_Turret.png';
  if (w.subtypeId === 'SmallGatlingGun') return 'icons/S__Gatling_Gun.png';
  if (w.subtypeId === 'SmallMissileLauncher') return 'icons/S__Missile_Launcher.png';
  return 'icons/L__Gatling_Avenger_Turret.png';
}

const wov = {};
const dups = [];
for (const w of weapons) {
  if (wov[w.subtypeId]) { dups.push(w.subtypeId); continue; }
  wov[w.subtypeId] = { id: w.id, name: w.name, icon: resolveIconFile(w) };
}
const mov = {};
for (const m of mags) {
  mov[m.subtypeId] = {
    category: m.category, localIcon: m.localIcon,
    roleMultiplier: m.roleMultiplier, defaultRUs: m.defaultRUs,
  };
}

const header = '// GENERATED by scratch/migrate_overrides.js — presentation-only overrides (ids/names/icons/labels).\n'
  + '// All numeric balance data is derived from CoreParts C# + Content/Data SBC via source_pipeline.js.\n'
  + '// Edit by hand only to change presentation (labels/icons); never to change balance numbers.\n'
  + 'const STUDIO_OVERRIDES = ';
fs.writeFileSync(
  path.join(dataDir, 'studio_overrides.js'),
  header + JSON.stringify({ weapons: wov, magazines: mov }, null, 2) + ';\n'
);
console.log('weapon overrides:', Object.keys(wov).length,
  '| duplicate subtypeIds skipped:', dups.length ? dups.join(', ') : 'none');
console.log('magazine overrides:', Object.keys(mov).length);
